git:
  submodules: false
os:
  - linux
  - osx
sudo: required
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=clang++; export CXX=clang++; export CXXFLAGS=-std=c++11; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi'
install:
  - sudo $(which npm) install --unsafe-perms
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
